name: Upload Artifact

on: push

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Generate report
        run: |
          echo "Test Report" > report.txt
          date >> report.txt
          cat report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.txt
