---
name: CICD
on:
  workflow_dispatch: null
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Checkc out code"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build  app
        run: echo "Build step"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "Deploy the app"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test app
        run: echo "Test app"
