name: hello

on:
  push:
    branches: main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello dosto"

      - name: say hello to username
        run: echo "hello $USER"

      - name: Print current date and time
        run: date

      - name: Print branch name
        run: echo "Branch name is ${{ github.ref_name }}"

      - name: List files in the repository
        run: ls -la

      - name: Print runner operating system
        run: echo "Runner OS is ${{ runner.os }}"

  details:
    runs-on: ubuntu-latest
    steps:
    - name: docker and python version
      run: docker --version && python --version

    
      
